### PR TITLE
Added Event Status Section

### PR DESCRIPTION
**Pull request by Shadows-of-Fire**
Minor fixes to other parts, like where @darkhax updated the Project Status %.
Probably could use some other formatting on the Event section, just not entirely sure what it needs.

### CODE REVIEW

**Comment by modmuss50** [comment]
Im not happy with having a list of events from forge and then adding them all in.

**Comment by Shadows-of-Fire** [comment]
I just cloned the Events issue. I'll admit it does look odd in its current state.

**Comment by modmuss50** [comment]
It may be better to have a list of the ones that have been added in

**Comment by Shadows-of-Fire** [comment]
Still could use some styling, but the right-content scheduled events are now a giant comment.

**Comment by Shadows-of-Fire** [comment]
So I switched it to just using the progress bar.  I kind of want to move the text to the center of the bar, but I'll leave that for later.

**Comment by modmuss50** [comment]
The merge issues need to be fixed.

**Comment by Shadows-of-Fire** [comment]
I fixed it.  It only took like 4 tries.

**Comment by modmuss50** [comment]
Nice thanks :)

**Pull request merged**
